# Generated by Django 2.1.3 on 2018-11-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
