# Generated by Django 2.1.3 on 2018-11-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181115_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.CharField(max_length=10),
        ),
    ]
