# Generated by Django 2.1.3 on 2018-11-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181120_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[(3, '3'), (4, '4'), (5, '5'), (6, '6')], max_length=5),
        ),
    ]
