# Generated by Django 2.1.3 on 2018-11-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181120_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_complete',
            field=models.BooleanField(default=0),
        ),
    ]
