# Generated by Django 2.1.3 on 2018-11-21 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20181120_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255)),
                ('department', models.CharField(choices=[('CSE', 'Computer Science'), ('ISE', 'Information Science')], max_length=10)),
                ('college', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('desigination', models.CharField(choices=[('Assistant Professer', 'Assistant Professer'), ('Head Of Department', 'HOD')], max_length=100)),
                ('experiences', models.TextField()),
                ('bio', models.TextField()),
                ('image_url', models.CharField(max_length=1000)),
                ('is_complete', models.BooleanField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
