# Generated by Django 2.1.3 on 2018-11-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20181121_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='experiences',
            field=models.TextField(),
        ),
    ]
