# Generated by Django 2.1.3 on 2018-11-22 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='db_schmea',
            new_name='db_schema',
        ),
    ]
