# Generated by Django 2.1.3 on 2018-12-03 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20181122_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Synopsis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('introduction', models.TextField()),
                ('objectives', models.TextField()),
                ('db_schema', models.TextField()),
                ('frontEnd', models.TextField()),
                ('backEnd', models.TextField()),
                ('requirements', models.TextField()),
                ('image_url', models.CharField(max_length=1000)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
    ]
